<Template>
    mainGrid:mainGrid
    gameOver:gameOver
    canvas.before:
        Color:
            rgba: (1, 1, 1, 1)
        Rectangle:
            size: 400,400
            source:'./assets/image/background.PNG'
            pos: self.pos
    GridLayout:
        cols: 1
        id: mainGrid
        size: 400,400
    Label:
        text: ""
        id: gameOver
        pos: (150,150)
        font_size: 45
        markup: True